project:
  type: website

website:
  title: "Robinson Amanyiraho"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/amanyiraho
      - icon: twitter
        href: https://x.com/amanyiraho
      - icon: envelope
        href: mailto:amanyiraho@gmail.com
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

